name: ladeco
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - HuggingFace::transformers=4.33
  - conda-forge::opencv
  - conda-forge::scipy
